blank_issues_enabled: false
contact_links:
  - name: Serveur Discord
    url: https://discord.gg/q6eMWS2
    about: Veuillez visiter notre serveur Discord pour toute question ou demande d'assistance.
