name: Issues Managing

# Controls when the workflow will run
on:
  issues:
    types:
      - labeled
      - edited

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Parsing issue form body # GitHub Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.3.0
      - name: Echo
        run: echo ${{ steps.parse.outputs.data }}
