name: Issues Managing

# Controls when the workflow will run
on:
  issues:
    types:
      - labeled
      - edited

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Parsing issue form body # GitHub Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.4.3
      - run: echo ${{ steps.parse.outputs.data }}
  bug_report:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'bug')
    needs:
      - process
    env:
      data: ${{ needs.process.steps.parse.outputs.data }}
    steps:
      - uses: actions/checkout@v2
      - name: Adding mod label
        if: contains(${{ env.data.bot-s-concerne-s-par-le-bug.text }}, 'KoroïMod')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: mod
      - name: Adding bot support label
        if: contains(env.data.bot-s-concerne-s-par-le-bug.text, 'Bot Support')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bot support
      - name: Adding mahoku label
        if: contains(env.data.bot-s-concerne-s-par-le-bug.text, 'Mahoku')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: mahoku
      - name: Adding web label
        if: contains(env.data.version-web-de-discord.text, '[x]')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: web
      - name: Adding priority label
        if: contains(env.data.priorite-du-probleme.text, 'Faible')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: priorité faible
      - name: Adding priority label
        if: contains(env.data.priorite-du-probleme.text, 'Moyenne')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: priorité moyenne
      - name: Adding priority label
        if: contains(env.data.priorite-du-probleme.text, 'Haute')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: priorité haute
      - name: Adding proprity label
        if: contains(env.data.priorite-du-probleme.text, 'Problème de sécurité')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: problème de sécurité
      - uses: actions-ecosystem/action-regex-match@v2
        id: match
        with:
          text: env.data.j-ai-teste-ce-probleme-sur-une-version-de-developpement-alpha-ou-beta.text
          regex: '^[A-Fa-f0-9]{7}$'
      - name: Adding dev label
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: dev
  feature_request:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'demande de fonctionnalité')
    needs:
      - process
    env:
      data: ${{ needs.process.steps.parse.outputs.data }}
    steps:
      - uses: actions/checkout@v2
      - name: Adding mod label
        if: contains(env.data.pour-quel-s-bot-s-cette-demande-de-fonctionnalite-est-elle-destinee.text, 'KoroïMod')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: mod
      - name: Adding bot support label
        if: contains(env.data.pour-quel-s-bot-s-cette-demande-de-fonctionnalite-est-elle-destinee.text, 'Bot Support')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bot support
      - name: Adding mahoku label
        if: contains(env.data.pour-quel-s-bot-s-cette-demande-de-fonctionnalite-est-elle-destinee.text, 'Mahoku')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: mahoku
